apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
spec:
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: ghcr.io/JerodBaxter/cinemaabyss/proxy-service:latest
        ports:
        - containerPort: 8080
